name: configuration_variable_example

on: workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      date: 13Feb
    steps:
      - name: Project details
        run: echo "Sponsor for the project is $owner & project id is ${{vars.PROJECT}}"
        env:
          owner: WHO
